run:
  concurrency: 2
  deadline: 1m
  skip-dirs:
    - vendor
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - maligned
    - staticcheck
    - structcheck
    - unconvert
    - varcheck